ALTER TABLE game ADD COLUMN quest_name VARCHAR(255);
ALTER TABLE game ADD COLUMN difficulty VARCHAR(10) NOT NULL DEFAULT 'NORMAL';
ALTER TABLE game ADD COLUMN second_wind BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE game ADD COLUMN gold INTEGER NOT NULL DEFAULT 0;

CREATE TABLE game_curse (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id         BIGINT NOT NULL REFERENCES game(id) ON DELETE CASCADE,
    curse_description VARCHAR(1000) NOT NULL
);

CREATE TABLE player_character (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id         BIGINT NOT NULL REFERENCES game(id) ON DELETE CASCADE,
    player_name     VARCHAR(255),
    character_name  VARCHAR(255),
    health          INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE player_card (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id    BIGINT NOT NULL REFERENCES player_character(id) ON DELETE CASCADE,
    card_name       VARCHAR(255) NOT NULL,
    card_source     VARCHAR(20)  NOT NULL,
    card_type       VARCHAR(20)  NOT NULL
);
